name: autopy-lot
on: [push]

jobs:
  build:
    name: autopy-lot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: autopy-lot 
        uses: deep5050/autopy-lot@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          check: all
          input_type: ipynb
          output_type: markdown
          output_dir: './docs/tutorial_/'